site_name: Segmentation of Large Language Models
theme: 
  name: material 
nav: 
  - Home: index.md
  - How it helps us: paper.md
  - Our Final Model: graphmodel.md
  - The Implementation: implement.md

extra:
  social:
    - icon: simple/github
      link: https://github.com/Vishnuprasadvbhat/redo_org
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/vishnuprasadvbhat/

